gemfile:
- Gemfile
language: ruby
rvm:
- 2.0.0
- 2.1.0
- 2.1.1
- 2.1.2
- 2.1.3
matrix:
  allow_failures:
  - rvm: 1.8.7
  - rvm: 1.9.2
  - rvm: 1.9.3
  - rvm: jruby-head
  - rvm: ruby-head
  - rvm: rbx
  fast_finish: true
